export const apple = [
  ['apple Grinning Face', '😀'],
  ['apple Grinning Cat', '😺'],
  ['apple Grinning Cat with Smiling Eyes', '😸'],
  ['apple Beaming Face with Smiling Eyes', '😁'],
  ['apple Grinning Face with Smiling Eyes', '😄'],
  ['apple Grinning Face with Sweat', '😅'],
  ['apple Face with Tears of Joy', '😂'],
  ['apple Cowboy Hat Face', '🤠'],
  ['apple Smiling Face with Smiling Eyes', '😊'],
  ['apple Squinting Face with Tongue', '😝'],
  ['apple Rolling on the Floor Laughing', '🤣'],
  ['apple Melting Face', '🫠'],
  ['apple Smiling Face with Tear', '🥲'],
  ['apple Star-Struck', '🤩'],
  ['apple Sun with Face', '🌞'],
  ['apple Smiling Face', '☺️'],
  ['apple Grinning Face with Big Eyes', '😃'],
  ['apple Partying Face', '🥳'],
  ['apple Smiling Face with Hearts', '🥰'],
  ['apple Face Savoring Food', '😋'],
  ['apple Smiling Face with Heart-Eyes', '😍'],
  ['apple Smiling Face with Sunglasses', '😎'],
  ['apple Smiling Cat with Heart-Eyes', '😻'],
  ['apple Smiling Face with Halo', '😇'],
  ['apple Smiling Face with Halo', '😇'],
]
