export const Body = [
  ['Brain', '🧠'],
  ['Anatomical Heart', '🫀'],
  ['Lungs', '🫁'],
  ['Tooth', '🦷'],
  ['Bone', '🦴'],
  ['Eyes', '👀'],
  ['Tongue', '👅'],
  ['Mouth', '👄'],
  ['Biting Lip', '🫦'],
  ['Footprints', '👣'],
  ['DNA', '🧬'],
  ['Drop of Blood', '🩸'],
  [''],
]

export const animal = [
  ['Monkey Face', '🐵'],
  ['Monkey', '🐒'],
  ['See-No-Evil Monkey', '🙈'],
  ['Hear-No-Evil Monkey', '🙉'],
  ['Speak-No-Evil Monkey', '🙊'],
  ['Gorilla', '🦍'],
  ['Orangutan', '🦧'],
  ['Dog Face', '🐶'],
  ['Dog', '🐕'],
  ['Service Dog', '🐕‍🦺'],
  ['Poodle', '🐩'],
  ['Wolf', '🐺'],
  ['Fox', '🦊'],
  ['Raccoon', '🦝'],
  ['Cat Face', '🐱'],
  ['Cat', '🐈'],
  ['Black Cat', '🐈‍⬛'],
  ['Lion', '🦁'],
  ['Tiger Face', '🐯'],
  ['Tiger', '🐅'],
  ['Leopard', '🐆'],
  ['Horse Face', '🐴'],
  ['Horse', '🐎'],
  ['Unicorn', '🦄'],
  ['Zebra', '🦓'],
  ['Donkey', '🫏'],
  ['Deer', '🦌'],
  ['Moose', '🫎'],
  ['Bison', '🦬'],
  ['Cow Face', '🐮'],
  ['ox', '🐂'],
  ['Water Buffalo', '🐃'],
  ['Cow', '🐄'],
  ['Pig Face', '🐷'],
  ['Pig', '🐖'],
  ['Boar', '🐗'],
  ['Pig Nose', '🐽'],
  ['Ram', '🐏'],
  ['Ewe', '🐑'],
  ['Goat', '🐐'],
  ['Camel', '🐪'],
  ['Two-Hump Camel', '🐫'],
  ['Llama', '🦙'],
  ['Giraffe', '🦒'],
  ['Elephant', '🐘'],
  ['Mammoth', '🦣'],
  ['Rhinoceros', '🦏'],
  ['Hippopotamus', '🦛'],
  ['Mouse Face', '🐭'],
  ['Mouse', '🐁'],
  ['Rat', '🐀'],
  ['Hamster', '🐹'],
  ['Rabbit Face', '🐰'],
  ['Rabbit', '🐇'],
  ['Chipmunk', '🐿️'],
  ['Beaver', '🦫'],
  ['Hedgehog', '🦔'],
  ['Bat', '🦇'],
  ['Bear', '🐻'],
  ['Polar Bear', '🐻‍❄️'],
  ['Koala', '🐨'],
  ['Panda', '🐼'],
  ['Sloth', '🦥'],
  ['Otter', '🦦'],
  ['Skunk', '🦨'],
  ['Paw Prints', '🐾'],
  ['Turkey', '🦃'],
  ['Chicken', '🐔'],
  ['Rooster', '🐓'],
  ['Hatching Chick', '🐣'],
  ['Baby Chick', '🐤'],
  ['Front-Facing Baby Chick', '🐥'],
  ['Bird', '🐦'],
  ['Black Bird', '🐦‍⬛'],
  ['Penguin', '🐧'],
  ['Dove', '🕊️'],
  ['Eagle', '🦅'],
  ['Duck', '🦆'],
  ['Swan', '🦢'],
  ['Goose', '🪿'],
  ['Owl', '🦉'],
  ['Dodo', '🦤'],
  ['Wing', '🪽'],
  ['Feather', '🪶'],
  ['Flamingo', '🦩'],
  ['Peacock', '🦚'],
  ['Parrot', '🦜'],
  ['Frog', '🐸'],
  ['Heart on Fire', '❤️‍🔥'],
  ['Broken Heart', '💔'],
  ['Fire', '🔥'],
  ['Hundred Points', '💯'],
  ['Hot Face', '🥵'],
  ['Face Screaming in Fear', '😱'],
  ['Angry Face with Horns', '🔥'],
  ['Smiling Face with Horns', '😈'],
  ['Angry Face with Horns', '👿'],
  ['Ghost', '👻'],
  ['Alien', '👽'],
  ['Alien Monster', '👾'],
  ['Robot', '🤖'],
  ['Candy', '🍬'],
  ['Lollipop', '🍭'],
  ['Fearful Face', '😨'],
  ['Clown Face', '🤡'],
  ['Orange Heart', '🧡'],
  ['Green Heart', '💚'],
  ['Purple Heart', '💜'],
  ['Grey Heart', '🩶'],
  ['Brown Heart', '🤎'],
  ['White Heart', '🤍'],
  ['Light Heart', '🩵'],
  ['Black Heart', '🖤'],
  ['Red Heart', '❤️'],
  ['Blue Heart', '💙'],
  ['Yellow Heart', '💛'],
  ['Rose', '🌹'],
  ['Smiling Face with Heart Eyes', '😍'],
  ['Heart with Arrow', '💘'],
  ['Beating Heart', '💓'],
  ['Pink Heart', '🩷'],
  ['Growing Heart', '💗'],
  ['Heart Exclamation', '❣️'],
  ['Mending Heart', '❤️‍🩹'],
  ['Nauseated Face', '🤢'],
  ['Drooling Face', '🤤'],
  ['Sneezing Face', '🤧'],
  ['Lying Face', '🤥'],
  ['Rocket', '🚀'],
  ['Rainbow', '🌈'],
  ['High Voltage', '⚡'],
]

export const Objects = [
  ['Glasses', '👓'],
  ['Sunglasses', '🕶️'],
  ['Mobile Phone', '📱'],
  ['Mobile Phone with Arrow', '📲'],
  ['Telephone', '☎️'],
  ['Telephone Receiver', '📞'],
  ['Pager', '📟'],
  ['Battery', '🔋'],
  ['Low Battery', '🪫'],
  ['Laptop', '💻'],
  ['Desktop Computer', '🖥️'],
  ['Pencil', '✏️'],
  ['Black Nib', '✒️'],
  ['Fountain Pen', '🖋️'],
  ['Pen', '🖊️'],
  ['Paintbrush', '🖌️'],
  ['Calendar', '📅'],
  ['Watch', '⌚'],
  ['Alarm Clock', '⏰'],
  ['Stopwatch', '⏱️'],
  ['Money Bag', '💰'],
  ['Light Bulb', '💡'],
  ['Bubbles', '🫧'],
  ['Toolbox', '🧰'],
  ['Gear', '⚙️'],
  ['Wrench', '🔧'],
  ['Hammer and Wrench', '🛠️'],
  ['Luggage', '🧳'],
  ['Flag: China', '🇨🇳'],
  ['Shaking Face', '🫨'],
  ['Pile of Poo', '💩'],
  ['Face in Clouds', '😶‍🌫️'],
  ['Dotted Line Face', '🫥'],
  ['Face Without Mouth', '😶'],
  ['Money-Mouth Face', '🤑'],
  ['Face with Hand Over Mouth', '🤭'],
  ['Smiling Face with Open Hands', '🤗'],
  ['Face with Open Eyes and Hand Over Mouth', '🫢'],
  ['Face with Peeking Eye', '🫣'],
  ['Shushing Face', '🤫'],
  ['Thinking Face', '🤔'],
  ['Saluting Face', '🫡'],
  ['Zipper-Mouth Face', '🤐'],
  ['Face with Raised Eyebrow', '🤨'],
  ['Neutral Face', '😐'],
  ['Expressionless Face', '😑'],
  ['Smirking Face', '😏'],
  ['Unamused Face', '😒'],
  ['Face with Rolling Eyes', '🙄'],
  ['Grimacing Face', '😬'],
  ['Face Exhaling', '😮‍💨'],
  ['Relieved Face', '😌'],
  ['Pensive Face', '😔'],
  ['Sleepy Face', '😪'],
  ['Sleeping Face', '😴'],
  ['Face with Medical Mask', '😷'],
  ['Face with Thermometer', '🤒'],
  ['Face with Head-Bandage', '🤕'],
  ['Face Vomiting', '🤮'],
  ['Cold Face', '🥶'],
  ['Woozy Face', '🥴'],
  ['Face with Crossed-Out Eyes', '😵'],
  ['Face with Spiral Eyes', '😵‍💫'],
  ['Exploding Head', '🤯'],
  ['Disguised Face', '🥸'],
  ['Nerd Face', '🤓'],
  ['Face with Monocle', '🧐'],
  ['Confused Face', '😕'],
  ['Face with Diagonal Mouth', '🫤'],
  ['Worried Face', '😟'],
  ['Slightly Frowning Face', '🙁'],
  ['Frowning Face', '☹️'],
  ['Face with Open Mouth', '😮'],
  ['Hushed Face', '😯'],
  ['Astonished Face', '😲'],
  ['Flushed Face', '😳'],
  ['Pleading Face', '🥺'],
  ['Face Holding Back Tears', '🥹'],
  ['Frowning Face with Open Mouth', '😦'],
  ['Anguished Face', '😧'],
  ['Sad but Relieved Face', '😥'],
  ['Crying Face', '😢'],
  ['Loudly Crying Face', '😭'],
  ['Confounded Face', '😖'],
  ['Persevering Face', '😣'],
  ['Disappointed Face', '😞'],
  ['Downcast Face', '😓'],
  ['Weary Face', '😩'],
  ['Tired Face', '😫'],
  ['Yawning Face', '🥱'],
  ['Face with Steam From Nose', '😤'],
  ['Enraged Face', '😡'],
  ['Angry Face', '😠'],
  ['Face with Symbols on Mouth', '🤬'],
  ['Upside-Down Face', '🙃'],
  ['Anxious Face with Sweat', '😰'],
]

export const food = [
  ['Hamburger', '🍔'],
  ['French Fries', '🍟'],
  ['Meat on Bone', '🍖'],
  ['Doughnut', '🍩'],
  ['Hot Beverage', '☕'],
  ['Beer Mug', '🍺'],
  ['Bubble Tea', '🧋'],
]

export const Symbols = [
  ['Check Mark Button', '✅'],
  ['Check Box with Check', '☑️'],
  ['Check Mark', '✔️'],
  ['Cross Mark', '❌'],
  ['Cross Mark Button', '❎'],
  ['Exclamation Question Mark', '⁉️'],
  ['Red Question Mark', '❓'],
  ['White Question Mark', '❔'],
  ['White Exclamation Mark', '❕'],
  ['Red Exclamation Mark', '❗'],
  ['Double Exclamation Mark', '‼️'],
  ['Wireless', '🛜'],
  ['Antenna Bars', '📶'],
  ['Up Arrow', '⬆️'],
  ['Right Arrow', '➡️'],
  ['Down Arrow', '⬇️'],
  ['Left Arrow', '⬅️'],
  ['Warning', '⚠️'],
  ['Water Closet', '🚾'],
  ['Zzz', '💤'],
  ['Speech Balloon', '💬'],
]

export const apple = [
  ['Grinning Face', '😀'],
  ['Grinning Cat', '😺'],
  ['Grinning Cat with Smiling Eyes', '😸'],
  ['Beaming Face with Smiling Eyes', '😁'],
  ['Grinning Face with Smiling Eyes', '😄'],
  ['Grinning Face with Sweat', '😅'],
  ['Face with Tears of Joy', '😂'],
  ['Cowboy Hat Face', '🤠'],
  ['Smiling Face with Smiling Eyes', '😊'],
  ['Squinting Face with Tongue', '😝'],
  ['Rolling on the Floor Laughing', '🤣'],
  ['Melting Face', '🫠'],
  ['Smiling Face with Tear', '🥲'],
  ['Star-Struck', '🤩'],
  ['Sun with Face', '🌞'],
  ['Smiling Face', '☺️'],
  ['Grinning Face with Big Eyes', '😃'],
  ['Partying Face', '🥳'],
  ['Smiling Face with Hearts', '🥰'],
  ['Face Savoring Food', '😋'],
  ['Smiling Face with Heart-Eyes', '😍'],
  ['Smiling Face with Sunglasses', '😎'],
  ['Smiling Cat with Heart-Eyes', '😻'],
  ['Smiling Face with Halo', '😇'],
  ['Smiling Face with Halo', '😇'],
  ...Body,
  ...Objects,
  ...Symbols,
  ...animal,
  ...food,
]
